package edu.csis.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import edu.csis.model.Account;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author bakumah
 */
public class AccountSummaryPage extends JFrame {
    protected Map<String, JButton> seeTransactionButtons = new HashMap<>();
    private JButton logOutButton;
    private JButton homeButton;
    private JPanel accountSummaryPanel;

    public AccountSummaryPage(List<Account> bankAccounts) {
        for (int i = 0; (i < bankAccounts.size() && i < 5); i++) {
            System.out.println(bankAccounts.get(i).getAccountNumber());
            System.out.println(bankAccounts.get(i).getAccountType());
            System.out.println(bankAccounts.get(i).getBalance());
            System.out.println(bankAccounts.get(i).getStatus());

            JButton see_transaction = new JButton("View Transaction");
            seeTransactionButtons.put(bankAccounts.get(i).getAccountNumber().toString(), see_transaction);
            accountSummaryPanel.add(see_transaction, new GridConstraints(2 + i, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 50), null, 0, false));
            accountSummaryPanel.add(new JLabel("Account #" + bankAccounts.get(i).getAccountNumber() + ":"), new GridConstraints(2 + i, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 50), null, 0, false));
            accountSummaryPanel.add(new JLabel("$" + bankAccounts.get(i).getBalance()), new GridConstraints(2 + i, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 50), null, 0, false));
        }

        initComponents();
    }

    private void initComponents() {

        // Set the mainPanel as the content pane of the JFrame
        setContentPane(accountSummaryPanel);

        // Set the title, default close operation, visibility, and pack the JFrame
        setTitle("KUMO Banking");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
        pack();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        accountSummaryPanel = new JPanel();
        accountSummaryPanel.setLayout(new GridLayoutManager(7, 3, new Insets(15, 30, 15, 30), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Account Summary");
        accountSummaryPanel.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logOutButton = new JButton();
        logOutButton.setText("Log Out");
        accountSummaryPanel.add(logOutButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 50), null, 0, false));
        homeButton = new JButton();
        homeButton.setText("Home");
        accountSummaryPanel.add(homeButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, 50), null, 0, false));
        final JSeparator separator1 = new JSeparator();
        accountSummaryPanel.add(separator1, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {return accountSummaryPanel;}

}
