spring:
    jpa:
        generate-ddl: true
        hibernate.ddl-auto: update
        database: default
        show-sql: true

    datasource:
        driver-class-name: org.apache.derby.iapi.jdbc.AutoloadedDriver
        url: jdbc:derby:final_project;create=true
        username: csis
        password: password
        type: com.zaxxer.hikari.HikariDataSource

logging:
    level:
        com.zaxxer.hikari: ERROR


